apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finals-chart.fullname" . }}-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "finals-chart.fullname" . }}-myapp
  template:
    metadata:
      labels:
        app: {{ include "finals-chart.fullname" . }}-myapp
    spec:
      containers:
        - name: myapp
          image: {{ .Values.myapp.image }}
          ports:
            - containerPort: {{ .Values.myapp.port }}
          env:
            - name: MONGODB_URI
              value: {{ .Values.myapp.environment.MONGODB_URI }}

---
#mongo deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finals-chart.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "finals-chart.name" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "finals-chart.name" . }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.environment.MONGO_INITDB_ROOT_USERNAME }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongo.environment.MONGO_INITDB_ROOT_PASSWORD }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-data
          emptyDir: {}
        - name: mongo-init
          configMap:
            name: mongo-initdb